#!/usr/bin/env bash

set -e

if [ $(uname -m) = 'arm64' ]; then
    CONFIG="install.conf.arm64.yaml"
elif [ $(uname -m) = 'x86_64' ]; then
    CONFIG="install.conf.x86_64.yaml"
else
    echo "Computer architecture unsupported ($(uname -m)). Exiting install."
    exit
fi

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
